added functionality for counting tfs 2010 users
raypereda/tfs-active-users pull request #1
Opened 2018-11-16 00:48 UTC by aluis94

Added a new flag -2010 for tfs 2010 user count.
Added a new history function for tfs 2010 that searches through the history of all 18 collections in tfs 2010.

2018-11-17 16:44 UTC, raypereda requested changes
Run "go fmt" on the code to the format the code. I have that turned on by default in my editor, VS Code.

2018-11-17 16:44 UTC, raypereda commented on main.go
> +var tfs2010Collections = [18]string{"CareSystems", "ClaimsEncounters", "CoreSystems","CorpSystemsNon-Erp", "CRM", "DBA","DefaultCollection","Encounters", "E-portal", "ITOps","Octo","ODSDWBI",
Wrap the long lines. Don't make readers have to scroll right to see what is going on.

2018-11-17 16:49 UTC, raypereda commented on main.go
> +	h := make([]string,0)
This is more idiomatic if you don't know the size 
```go
var h []string
```
See here https://stackoverflow.com/questions/25543520/declare-slice-or-make-slice

2018-11-17 16:52 UTC, raypereda commented on main.go
> +			combined=append(combined,h[2:]...)
Nice use of  `... append(combined, h[2:]...)`

2018-11-17 16:53 UTC, raypereda requested changes
Address the changes, especially the `go fmt`, and I'll review again.

2018-11-19 17:01 UTC, aluis94 commented on main.go
> +var tfs2010Collections = [18]string{"CareSystems", "ClaimsEncounters", "CoreSystems", "CorpSystemsNon-Erp", "CRM",
Word wrapped this string and ran go fmt

2018-11-19 17:23 UTC, aluis94 commented on main.go
> +	var h []string
Changed string array initialization

2018-11-20 19:42 UTC, raypereda commented
:+1: Nice job @aluis94

2018-11-20 19:42 UTC, merged